spring:
#  mvc:
#    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  level:
    root: ERROR
    by.nbarysevich: debug
    org.springframework.web: INFO
server:
  error:
    whitelabel:
      enabled: false
  address: 0.0.0.0
  ssl:
    key-alias: tomcat
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
    enabled: true
  port: 443


